# @name get-prompts
GET http://localhost:3333/clients

###

# @name create-new-client
POST http://localhost:3333/client
Content-Type: application/json

{
    "name": "name",
    "number": "number",
    "address": "address"
}

###

# @name create-new-client-2
POST http://localhost:3333/client
Content-Type: application/json

{
    "name": "name",
    "number": "number",
    "address": "address"
}

###

# @name get-client-by-id
GET http://localhost:3333/client/a762ed53-0cca-42bf-89ac-0fccde574118

### 

# @name update-client
PUT http://localhost:3333/client/a762ed53-0cca-42bf-89ac-0fccde574118
Content-Type: application/json

{
    "name": "new name"
}

### 

# @name delete-client
DELETE http://localhost:3333/client/8481a79b-7d4f-41c0-9131-2389ebeb2256
