# @name get-prompts
GET http://localhost:3333/clients

###

# @name create-new-client
POST http://localhost:3333/client
Content-Type: application/json

{
    "name": "Rosangela",
    "number": "41995641273",
    "address": "Rua Rio Grande do Sul, 123"
}

###

# @name create-new-client-2
POST http://localhost:3333/client
Content-Type: application/json

{
    "name": "Pedro",
    "number": "41999202325",
    "address": "Rua Santos Grande, 155"
}

###

# @name get-client-by-id
GET http://localhost:3333/client/a762ed53-0cca-42bf-89ac-0fccde574118

### 

# @name update-client
PUT http://localhost:3333/client/a762ed53-0cca-42bf-89ac-0fccde574118
Content-Type: application/json

{
    "name": "Igor Oliveira de Souza"
}

### 

# @name delete-client
DELETE http://localhost:3333/client/8481a79b-7d4f-41c0-9131-2389ebeb2256
